from __future__ import annotations

from pathlib import Path
import tempfile
import subprocess
import sys

import rich

from ._nbconvert import new_notebook, code_cell, write_ipynb
from ._pep723 import parse_inline_script_metadata, extract_inline_meta


def new_notebook_with_inline_metadata(dir: Path, python: str | None = None) -> dict:
    """Create a new notebook with inline metadata.

    Parameters
    ----------
    dir : pathlib.Path
        A directory for uv to run `uv init` in. This is used so that we can
        defer the selection of Python (if not specified) to uv.
    python : str, optional
        A version of the Python interpreter. Provided as `--python` to uv if specified.

    Returns
    -------
    dict
        A new notebook with a single code cell containing the contents of the
        script generated by `uv init`.
    """
    with tempfile.NamedTemporaryFile(
        mode="w+",
        suffix=".py",
        delete=True,
        dir=dir,
    ) as f:
        cmd = ["uv", "init", "--quiet"]
        if python:
            cmd.extend(["--python", python])
        cmd.extend(["--script", f.name])

        subprocess.run(cmd, check=True)
        f.seek(0)
        contents = f.read().strip()
        inline_meta, script = extract_inline_meta(contents)
        cells = [code_cell(script, hidden=True)]
        if inline_meta:
            cells.insert(0, code_cell(inline_meta.strip(), hidden=True))
        notebook = new_notebook(cells=cells)

    return notebook


def get_first_non_conflicting_untitled_ipynb(dir: Path) -> Path:
    base_name = "Untitled"
    for i in range(100):
        filename = f"{base_name}{i if i > 0 else ''}.ipynb"
        path = dir / filename
        if not path.exists():
            return path

    raise ValueError("Could not find an available UntitledX.ipynb")


def init(
    path: Path | None,
    python: str | None,
) -> None:
    """Initialize a new notebook."""
    if not path:
        path = get_first_non_conflicting_untitled_ipynb(Path.cwd())

    if path.suffix != ".ipynb":
        rich.print("File must have a `[cyan].ipynb[/cyan]` extension.", file=sys.stderr)
        sys.exit(1)

    notebook = new_notebook_with_inline_metadata(path.parent, python)
    write_ipynb(notebook, path)

    rich.print(f"Initialized notebook at `[cyan]{path.resolve().absolute()}[/cyan]`")