from __future__ import annotations

import sys
import typing
from pathlib import Path
import tempfile
import subprocess

import rich

from ._nbconvert import new_notebook, code_cell, write_ipynb
from ._add import add


def new_notebook_with_inline_metadata(dir: Path, python: str | None = None) -> dict:
    """Create a new notebook with inline metadata.

    This function initializes a new notebook by running `uv init` in the specified directory.
    It captures the output script and embeds it into a new Jupyter notebook with a hidden code cell.

    Parameters
    ----------
    dir : pathlib.Path
        The directory where `uv init` will be executed. This is used to defer the selection of the Python interpreter
        to `uv` if not specified.
    python : str, optional
        The version of the Python interpreter to be used. If provided, it is passed to `uv` as `--python`.

    Returns
    -------
    dict
        A new notebook dictionary with a single code cell containing the script generated by `uv init`.
    """
    with tempfile.NamedTemporaryFile(
        mode="w+",
        suffix=".py",
        delete=True,
        dir=dir,
    ) as f:
        cmd = ["uv", "init", "--quiet"]
        if python:
            cmd.extend(["--python", python])
        cmd.extend(["--script", f.name])

        subprocess.run(cmd)
        f.seek(0)
        contents = f.read().strip()
        notebook = new_notebook(cells=[code_cell(contents, hidden=True)])

    return notebook


def get_first_non_conflicting_untitled_ipynb(dir: Path) -> Path:
    """Find the first available Untitled notebook file in the specified directory.

    This function checks for the existence of Untitled.ipynb and subsequent UntitledX.ipynb files
    until it finds an available name.

    Parameters
    ----------
    dir : pathlib.Path
        The directory to search for available Untitled notebook files.

    Returns
    -------
    pathlib.Path
        The path to the first available Untitled notebook file.

    Raises
    ------
    ValueError
        If no available UntitledX.ipynb file is found within the first 100 attempts.
    """
    if not (dir / "Untitled.ipynb").exists():
        return dir / "Untitled.ipynb"

    for i in range(1, 100):
        if not (dir / f"Untitled{i}.ipynb").exists():
            return dir / f"Untitled{i}.ipynb"

    raise ValueError("Could not find an available UntitledX.ipynb")


def init(
    path: Path | None = None,
    python: str | None = None,
    packages: typing.Sequence[str] = [],
) -> None:
    """Initialize a new notebook.

    This function initializes a new Jupyter notebook with optional Python version and additional packages.
    If no path is provided, it creates a new notebook with a default name in the current working directory.

    Parameters
    ----------
    path : pathlib.Path, optional
        The path to the notebook file. If not provided, a new file will be created.
    python : str, optional
        The version of the Python interpreter to use.
    packages : typing.Sequence[str], optional
        A list of packages to add to the notebook.

    Raises
    ------
    SystemExit
        If the file does not have a `.ipynb` extension.
    """
    if not path:
        path = get_first_non_conflicting_untitled_ipynb(Path.cwd())

    if not path.suffix == ".ipynb":
        rich.print("File must have a `[cyan].ipynb[/cyan]` extension.", file=sys.stderr)
        sys.exit(1)

    notebook = new_notebook_with_inline_metadata(path.parent, python)
    write_ipynb(notebook, path)

    if len(packages) > 0:
        add(path, packages, requirements=None)

    rich.print(f"Initialized notebook at `[cyan]{path.resolve().absolute()}[/cyan]`")